### ISSUE TITLE
Duplicated functions/tools in the repo

### ISSUE THREAD

**Issue by nunoguedelha** [dic-iit/matlab-whole-body-simulators#4]
Hi @Giulero , I noticed the minor following problems with the tools in `src/tools`:
- The tools `expinential_map`, `H2Rp`, Rp2H` are redefined in the classes. I guess their implementation in the folder `src/tools` was just the first step...
- In the classes, you sometimes use `wbc.skew`, and sometimes use `skew`. I guess the second case is a leftover right?

As a consequence, I suggest we remove all of them except `get_R_dot`, which actually isn't used anywhere yet, unless I missed something.

I can do it in my PR if you agree.

**Comment by nunoguedelha** [comment]
More precisely, the 3 mentioned tools are defined as static methods of class `State`.

**Comment by Giulero** [comment]
Hi @nunoguedelha! Sure! You could remove also `get_R_dot`. I was using it when $\dot{R}$ was integrated, while now the simulator uses the exponential map.

**Comment by nunoguedelha** [comment]
Great!

**Comment by nunoguedelha** [comment]
Fixed by #3 .
